from sqlalchemy.orm import Session
import models
import schemas
from typing import List

def get_project(db: Session, project_id: str) -> models.Project:
    """
    Fetches a project by ID. Returns None if not found.
    """
    return db.query(models.Project).filter(models.Project.id == project_id).first()

def create_compliance_alerts(db: Session, project_id: str, alerts: List[schemas.ComplianceAlert]):
    """
    Takes a list of Pydantic ComplianceAlert schemas (generated by our Rules Engine)
    and saves them to the PostgreSQL database.
    """
    db_alerts = []
    for alert in alerts:
        db_alert = models.ComplianceAlertModel(
            project_id=project_id,
            alert_type=alert.type,
            message=alert.message,
            severity=alert.severity
        )
        db.add(db_alert)
        db_alerts.append(db_alert)
    
    db.commit()
    return True

def check_blockchain_verification(db: Session, project_id: str) -> bool:
    """
    Checks if the project has a valid and verified blockchain ledger entry.
    """
    record = db.query(models.BlockchainLedger).filter(
        models.BlockchainLedger.project_id == project_id
    ).order_by(models.BlockchainLedger.created_at.desc()).first()
    
    if record and record.verified:
        return True
    return False
