// ==========================================================================
// NIRMAAN MPLADS AUDIT PLATFORM - DYNAMIC BILINGUAL ENGINE
// Independent Infrastructure Audit & Early Warning System
// ==========================================================================

let currentLang = 'en'; // 'en' | 'hi'
let govPersona = 'ministry';

// Translations Dictionary (Independent Platform Terminology)
const TRANSLATIONS = {
 en: {
 topGovText: '',
 satyamev: 'MINISTRY OF STATISTICS AND PROGRAMME IMPLEMENTATION',
 skipContent: 'Skip to Main Content',
 ministryTitle: 'NIRMAAN — MPLADS AI Infrastructure Audit & Compliance Platform',
 ministryGov: '',
 ministrySub: 'Autonomous Multi-Oracle Compliance Engine & Fraud Analytics System',
 navHome: 'Home',
 navAbout: 'About',
 navAudit: 'Audit Command Center',
 navState: 'State Reports',
 navMp: 'MP Portal',
 navHelp: 'Helpdesk',
 navLogin: ' Auditor Login',
 navBack: ' Back to Landing Page',
 tickerLabel: 'System Update:',
 tickerText: ' Platform Update: AI Early Warning Audit System for FY 2025-26 MPLADS Disbursals is now ACTIVE across all 543 Constituencies.',
 personaSelectLabel: 'Select Stakeholder Persona View:',
 btnMinistry: ' Central Executive View',
 btnState: ' State Nodal View',
 btnDistrict: ' District Authority View',
 btnMp: ' MP Portal View',
 searchHeading: ' Search & Audit MPLADS Project Sanction',
 searchDesc: 'Enter a Project ID to inspect AI compliance warnings, physical vs financial disbursal gaps, and blockchain audit logs.',
 searchInputPlaceholder: 'Enter Project ID (e.g., PROJ-999, PROJ-101)...',
 searchBtn: ' Audit Project Search',
 presetLabel: 'Quick Audit Presets:',
 presetHighRisk: 'PROJ-999 (High Priority Audit Flag)',
 presetOnTrack: 'PROJ-101 (Standard Progress)',
 dashboardsTitle: ' Stakeholder Audit Command Dashboards',
 cardMinistryTitle: ' 1. Central Executive View',
 cardMinistryDesc: 'Macro fund utilization analytics, state-wise compliance rankings, and high-priority national flags.',
 cardStateTitle: ' 2. State Nodal Authority View',
 cardStateDesc: 'State-wide fund disbursals, district-level compliance rankings, and pending sanction reviews.',
 cardDistrictTitle: ' 3. District Authority View',
 cardDistrictDesc: 'Executing agency performance tracking, drone/photo EXIF milestone queue, and compliance notice issuance.',
 cardMpTitle: ' 4. Member of Parliament (MP) View',
 cardMpDesc: 'Constituency recommended works, real-time physical progress tracking, and citizen transparency log.',
 launchBtn: 'Launch View',
 specHeading: ' Project Audit Specification',
 highPriorityTag: 'High Priority Audit Flag',
 hashVerifiedTag: ' Blockchain Hash Verified',
 alertsHeader: ' Active Compliance Action Feed',
 alertsDesc: 'Actionable compliance notices generated by Rules Engine based on MPLADS guidelines.',
 satHeader: ' Satellite & Drone Verification',
 satDesc: 'Sentinel-2 imagery & EXIF photo metadata validation container.',
 fetchSatBtn: ' Fetch Sentinel-2 Satellite Overlay',
 auditExifBtn: ' Audit EXIF Photo Geofence',
 gnnHeader: ' Contractor Matrix (GNN Graph)',
 gnnDesc: 'Graph Neural Network (GCN) analysis of shared bank accounts and circular bidding.',
 gnnBox: '[ Marut Construction Ltd. Relational Network Graph ]',
 satBoxTitle: '[ Mapbox GL / PostGIS Spatial View Placeholder ]',
 btnNotice: ' Issue Compliance Notice',
 btnFreeze: ' Freeze Disbursal',
 btnHash: ' Verify Hash',
 recAction: 'Recommended Action:',
 disbursedLabel: 'Financial Disbursed:',
 progressLabel: 'Verified Physical Progress:',
 gapLabel: 'Progress Gap:',
 footerLinks: 'Important Links',
 footerPolicies: 'Policies & Support',
 footerContact: 'Contact Hub',
 footerManagedBy: 'NIRMAAN — AI-Driven Compliance & Audit Protocol for MPLADS Infrastructure Projects.',
 footerHostedBy: 'Platform System Architecture & Immutable Ledger Engine | Content Ownership: NIRMAAN Audit Engine'
 },
 hi: {
 topGovText: '',
 satyamev: 'निर्माण अनुपालन प्रणाली (NIRMAAN System)',
 skipContent: 'मुख्य विषयवस्तु पर जाएं',
 ministryTitle: 'निर्माण (NIRMAAN) — एमपीलैड्स एआई इन्फ्रास्ट्रक्चर ऑडिट प्लेटफॉर्म',
 ministryGov: '',
 ministrySub: 'स्वायत्त मल्टी-ओरैकल अनुपालन इंजन एवं धोखाधड़ी विश्लेषण प्रणाली',
 navHome: 'मुख्य पृष्ठ',
 navAbout: 'हमारे बारे में',
 navAudit: 'ऑडिट कमांड केंद्र',
 navState: 'राज्य रिपोर्ट',
 navMp: 'सांसद पोर्टल',
 navHelp: 'सहायता केंद्र',
 navLogin: ' ऑडिटर लॉगिन',
 navBack: ' मुख्य पृष्ठ पर लौटें',
 tickerLabel: 'सिस्टम सूचना:',
 tickerText: ' प्लेटफॉर्म अपडेट: MPLADS FY 2025-26 संवितरण हेतु एआई आधारित प्रारंभिक चेतावनी ऑडिट प्रणाली सक्रिय है।',
 personaSelectLabel: 'ऑडिट दृष्टिकोण बदलें (Select Audit Persona):',
 btnMinistry: ' केंद्रीय कार्यकारी दृष्टिकोण',
 btnState: ' राज्य नोडल दृष्टिकोण',
 btnDistrict: ' जिला प्राधिकरण दृष्टिकोण',
 btnMp: ' सांसद पोर्टल दृष्टिकोण',
 searchHeading: ' MPLADS कार्य स्वीकृतियों की त्वरित खोज एवं ऑडिट',
 searchDesc: 'परियोजना संख्या दर्ज कर एआई अनुपालन चेतावनियां, वित्तीय बनाम भौतिक प्रगति अंतर एवं ब्लॉकचेन बहीखाता जांचें।',
 searchInputPlaceholder: 'परियोजना संख्या दर्ज करें (उदा. PROJ-999, PROJ-101)...',
 searchBtn: ' खोजें एवं ऑडिट करें',
 presetLabel: 'त्वरित ऑडिट नमूना:',
 presetHighRisk: 'PROJ-999 (उच्च जोखिम अलर्ट / High Risk)',
 presetOnTrack: 'PROJ-101 (मानक प्रगति / On Track)',
 dashboardsTitle: ' हितधारक ऑडिट कमांड सेंटर डैशबोर्ड',
 cardMinistryTitle: ' 1. केंद्रीय कार्यकारी दृष्टिकोण',
 cardMinistryDesc: 'राष्ट्रीय स्तर पर निधियों के उपयोग, राज्य-वार रैंकिंग एवं उच्च स्तरीय ऑडिट चेतावनियों की निगरानी।',
 cardStateTitle: ' 2. राज्य नोडल प्राधिकरण दृष्टिकोण',
 cardStateDesc: 'राज्य के जिलों में निधियों के संवितरण, लंबित स्वीकृतियों एवं कार्य प्रगति अंतर की जांच।',
 cardDistrictTitle: ' 3. जिला प्राधिकरण दृष्टिकोण',
 cardDistrictDesc: 'स्थानीय ठेकेदार प्रदर्शन मैट्रिक्स, स्थल फोटो EXIF सत्यापन कतार एवं कारण बताओ नोटिस जारी करना।',
 cardMpTitle: ' 4. सांसद पोर्टल दृष्टिकोण',
 cardMpDesc: 'संसदीय क्षेत्र के अनुशंसित विकास कार्यों की स्थिति, स्वीकृतियां एवं पारदर्शी नागरिक रिपोर्टिंग।',
 launchBtn: 'पोर्टल खोलें',
 specHeading: ' परियोजना ऑडिट विवरण (Project Specification)',
 highPriorityTag: 'उच्च प्राथमिकता ऑडिट',
 hashVerifiedTag: ' ब्लॉकचेन बहीखाता सत्यापित',
 alertsHeader: ' अनुपालन सूचनाएं (Action Feed)',
 alertsDesc: 'एमपीलैड्स नियमों के अनुसार स्वचालित अलर्ट।',
 satHeader: ' उपग्रह एवं ड्रोन फोटो सत्यापन',
 satDesc: 'सेन्टिनेल-2 उपग्रह चित्र एवं EXIF जियो-टैग सत्यापन कंटेनर।',
 fetchSatBtn: ' उपग्रह चित्र प्राप्त करें (Sentinel-2)',
 auditExifBtn: ' फोटो EXIF ऑडिट (Geofence)',
 gnnHeader: ' ठेकेदार सांठगांठ जांच (GNN Graph)',
 gnnDesc: 'Graph Neural Network (GCN) द्वारा साझा बैंक खातों एवं बोली सांठगांठ का ऑडिट।',
 gnnBox: '[ मुरुत कंस्ट्रक्शन लि. नेटवर्क ग्राफ ]',
 satBoxTitle: '[ Mapbox GL / PostGIS भू-स्थानिक मानचित्र ]',
 btnNotice: ' कारण बताओ नोटिस जारी करें',
 btnFreeze: ' भुगतान पर रोक लगाएं',
 btnHash: ' ऑन-चेन हैश जांचें',
 recAction: 'अनुशंसित कार्रवाई (Required Action):',
 disbursedLabel: 'जारी की गई वित्तीय राशि:',
 progressLabel: 'सत्यापित भौतिक प्रगति:',
 gapLabel: 'प्रगति अंतर (Gap):',
 footerLinks: 'महत्वपूर्ण लिंक',
 footerPolicies: 'नीति एवं सहायता',
 footerContact: 'संपर्क केंद्र',
 footerManagedBy: 'NIRMAAN — एमपीलैड्स बुनियादी ढांचा परियोजनाओं हेतु एआई ऑडिट प्रोटोकॉल।',
 footerHostedBy: 'सिस्टम आर्किटेक्चर एवं ब्लॉकचेन लेजर इंजन | कंटेंट स्वामित्व: NIRMAAN ऑडिट इंजन'
 }
};

// Stakeholder Persona Configurations
const GOV_PERSONAS = {
 en: {
 ministry: {
 key: 'ministry',
 title: ' Central Executive Command Center',
 subtitle: 'National MPLADS Audit Command Center & Early Warning System',
 metrics: [
 { title: 'Total Active Projects', value: '42,850', sub: 'Across 543 Constituencies', type: 'normal' },
 { title: 'Total Sanctioned Funds', value: '₹2,142.50 Cr', sub: 'FY 2025-26 Allocation', type: 'normal' },
 { title: 'High-Priority Audit Alerts', value: '312 Warnings', sub: 'Requires Priority Inspection', type: 'danger' },
 { title: 'Avg Physical Progress', value: '64.2%', sub: 'vs 81.5% Disbursal Rate', type: 'warning' }
 ]
 },
 state: {
 key: 'state',
 title: ' State Nodal Authority (Rajasthan)',
 subtitle: 'State-Level MPLADS Compliance Monitoring & District Performance Rankings',
 metrics: [
 { title: 'State Sanctioned Works', value: '3,120 Works', sub: '25 Districts Monitored', type: 'normal' },
 { title: 'State Released Funds', value: '₹156.00 Cr', sub: 'State Nodal Account', type: 'normal' },
 { title: 'Progress Deviation Flags', value: '28 Flags', sub: 'Physical vs Financial Variance', type: 'danger' },
 { title: 'Avg Completion Duration', value: '184 Days', sub: 'Forecasted Delay: +22 Days', type: 'warning' }
 ]
 },
 district: {
 key: 'district',
 title: ' District Collectorate (Jaipur District)',
 subtitle: 'Local Executing Agencies, Contractor Tracking & Photo Verification Queue',
 metrics: [
 { title: 'District Sanctioned Works', value: '184 Works', sub: '12 Executing Agencies', type: 'normal' },
 { title: 'Pending EXIF Photo Queue', value: '14 Queued', sub: 'Awaiting Drone/Photo Audit', type: 'warning' },
 { title: 'Contractor Risk Flags', value: '4 Agencies', sub: 'Circular Collusion Suspected', type: 'danger' },
 { title: 'Utilized Funds', value: '₹9.20 Cr', sub: '82% Utilization Rate', type: 'success' }
 ]
 },
 mp: {
 key: 'mp',
 title: ' Member of Parliament Portal (Jaipur Rural Constituency)',
 subtitle: 'Constituency Work Recommendations, Real-Time Progress & Citizen Visibility',
 metrics: [
 { title: 'Recommended Works', value: '35 Projects', sub: 'Total Value: ₹5.00 Cr', type: 'normal' },
 { title: 'Sanctioned & In-Progress', value: '28 Projects', sub: '80% Sanction Rate', type: 'success' },
 { title: 'Completed Works', value: '18 Projects', sub: 'On-Chain Verified', type: 'success' },
 { title: 'Forecasted Delays', value: '3 Projects', sub: 'Contractor Delay Warnings', type: 'warning' }
 ]
 }
 },
 hi: {
 ministry: {
 key: 'ministry',
 title: ' केंद्रीय कार्यकारी कमांड सेंटर',
 subtitle: 'राष्ट्रीय सांसद स्थानीय क्षेत्र विकास योजना (MPLADS) ऑडिट कमांड सेंटर',
 metrics: [
 { title: 'कुल सक्रिय परियोजनाएं', value: '42,850', sub: '543 संसदीय क्षेत्रों में', type: 'normal' },
 { title: 'स्वीकृत निधि (Sanctioned)', value: '₹2,142.50 Cr', sub: 'वित्तीय वर्ष 2025-26', type: 'normal' },
 { title: 'उच्च प्राथमिकता ऑडिट फ्लैग', value: '312 Warnings', sub: 'केंद्रीय निरीक्षण हेतु', type: 'danger' },
 { title: 'औसत भौतिक प्रगति', value: '64.2%', sub: 'बनाम 81.5% संवितरण दर', type: 'warning' }
 ]
 },
 state: {
 key: 'state',
 title: ' राज्य नोडल प्राधिकरण (राजस्थान)',
 subtitle: 'राज्य स्तरीय अनुपालन निगरानी एवं जिला रैंकिंग पोर्टल',
 metrics: [
 { title: 'राज्य में स्वीकृत कार्य', value: '3,120 Works', sub: '25 जिले शामिल', type: 'normal' },
 { title: 'जारी निधि (State Release)', value: '₹156.00 Cr', sub: 'राज्य नोडल खाता', type: 'normal' },
 { title: 'भौतिक अंतर चेतावनी', value: '28 Flags', sub: 'वित्तीय बनाम भौतिक असंतुलन', type: 'danger' },
 { title: 'औसत कार्य अवधि', value: '184 Days', sub: 'पूर्वानुमानित विलंब: +22 दिन', type: 'warning' }
 ]
 },
 district: {
 key: 'district',
 title: ' जिला मजिस्ट्रेट / कलेक्टर कार्यालय (जयपुर)',
 subtitle: 'स्थानीय कार्यन्वयन एजेंसी, ठेकेदार ट्रैकिंग एवं ड्रोन सत्यापन कतार',
 metrics: [
 { title: 'जिले में स्वीकृत कार्य', value: '184 Works', sub: '12 कार्यन्वयन एजेंसियां', type: 'normal' },
 { title: 'लंबित EXIF फोटो सत्यापन', value: '14 Queued', sub: 'ड्रोन/स्थान जांच हेतु', type: 'warning' },
 { title: 'ठेकेदार जोखिम फ्लैग', value: '4 Agencies', sub: 'कपटपूर्ण पुनरावृत्ति संदेह', type: 'danger' },
 { title: 'उपयोग की गई राशि', value: '₹9.20 Cr', sub: '82% उपयोग दर', type: 'success' }
 ]
 },
 mp: {
 key: 'mp',
 title: ' सांसद पोर्टल (जयपुर ग्रामीण)',
 subtitle: 'अनुशंसित विकास कार्य, वास्तविक समय प्रगति एवं पारदर्शिता',
 metrics: [
 { title: 'अनुशंसित कार्य', value: '35 Projects', sub: 'कुल मूल्य: ₹5.00 Cr', type: 'normal' },
 { title: 'स्वीकृत एवं प्रगति पर', value: '28 Projects', sub: '80% स्वीकृति दर', type: 'success' },
 { title: 'पूर्ण हुए कार्य', value: '18 Projects', sub: 'ऑन-चेन सत्यापित', type: 'success' },
 { title: 'पूर्वानुमानित विलंब', value: '3 Projects', sub: 'ठेकेदार विलंब चेतावनी', type: 'warning' }
 ]
 }
 }
};

const GOV_ALERTS_DB = {
  'en': {
    'PROJ-001': {
      id: 'PROJ-001',
      title: 'Primary School Renovation',
      agency: 'Apex Builders Ltd.',
      state: 'Karnataka',
      district: 'Bengaluru Urban',
      constituency: 'Bengaluru South',
      sanctionedAmount: '₹50 Lakhs',
      disbursedPercent: 10,
      physicalProgressPercent: 12,
      bc_status: 'VERIFIED',
      bc_hash: '0x1a2b...9c8d',
      alerts: [] // No alerts, baseline
    },
    'PROJ-999': {
      id: 'PROJ-999',
      title: 'Water Treatment Plant & Community Facility Construction',
      agency: 'Marut Construction Ltd.',
      state: 'Rajasthan',
      district: 'Jaipur',
      constituency: 'Jaipur Rural',
      sanctionedAmount: '₹1.50 Crore',
      disbursedPercent: 75,
      physicalProgressPercent: 20,
      bc_status: 'VERIFIED',
      bc_hash: '0x5FbDB2315678afecb367f032d93F642f64180aa3', // From Hardhat output
      alerts: [
        {
          type: 'FINANCIAL_DISCREPANCY',
          severity: 'CRITICAL',
          title: '🚨 Financial Progress Discrepancy (Isolation Forest)',
          message: '75% of sanctioned funds (₹1.125 Crore) have been disbursed, but verified physical milestone progress is only 20%. 55% deviation from compliance guidelines.',
          actionRequired: 'Freeze further financial release until District Collector conducts physical inspection.'
        },
        {
          type: 'DUPLICATE_PROPOSAL',
          severity: 'HIGH',
          title: '⚠️ Duplicate Proposal Flag (FAISS / NLP)',
          message: 'Semantic similarity match (89.2%) detected with historically completed project "Community Water Center" in adjacent block (FY 2021-22). Possible Double-Dipping attempt.',
          actionRequired: 'Cross-reference GIS coordinates with PROJ-2021-442.'
        },
        {
          type: 'PREDICTIVE_DELAY',
          severity: 'MEDIUM',
          title: '⚠️ Predictive Delay Risk (XGBoost)',
          message: 'Current milestone completion rate indicates a 92% probability of 4+ months delay beyond expected completion date.',
          actionRequired: 'Issue formal notice to State Nodal Agency for expedited material procurement.'
        }
      ]
    },
    'PROJ-SAFE': {
      id: 'PROJ-SAFE',
      title: 'Solar Street Lighting Installation',
      agency: 'EcoPower Solutions',
      state: 'Gujarat',
      district: 'Surat',
      constituency: 'Surat',
      sanctionedAmount: '₹2.00 Crore',
      disbursedPercent: 100,
      physicalProgressPercent: 100,
      bc_status: 'VERIFIED',
      bc_hash: '0x8f2a...391c',
      alerts: []
    }
  },
  'hi': {

    'PROJ-001': {
      id: 'PROJ-001',
      title: 'प्राथमिक विद्यालय नवीनीकरण',
      agency: 'एपेक्स बिल्डर्स लि.',
      state: 'कर्नाटक',
      district: 'बेंगलुरु शहरी',
      constituency: 'बेंगलुरु दक्षिण',
      sanctionedAmount: '₹50 लाख',
      disbursedPercent: 10,
      physicalProgressPercent: 12,
      bc_status: 'VERIFIED',
      bc_hash: '0x1a2b...9c8d',
      alerts: []
    },
    'PROJ-999': {
      id: 'PROJ-999',
      title: 'जल शोधन संयंत्र एवं सामुदायिक भवन निर्माण',
      agency: 'मुरुत कंस्ट्रक्शन लि.',
      state: 'राजस्थान',
      district: 'जयपुर',
      constituency: 'जयपुर ग्रामीण',
      sanctionedAmount: '₹1.50 करोड़',
      disbursedPercent: 75,
      physicalProgressPercent: 20,
      bc_status: 'VERIFIED',
      bc_hash: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
      alerts: [
        {
          type: 'FINANCIAL_DISCREPANCY',
          severity: 'CRITICAL',
          title: '🚨 वित्तीय प्रगति में गंभीर विचलन',
          message: '75% स्वीकृत निधि जारी की जा चुकी है, जबकि भौतिक प्रगति केवल 20% है।',
          actionRequired: 'जिला कलेक्टर द्वारा भौतिक सत्यापन किए जाने तक अगली किस्त पर रोक लगाएं।'
        }
      ]
    },
    'PROJ-SAFE': {
      id: 'PROJ-SAFE',
      title: 'सौर स्ट्रीट लाइटिंग स्थापना',
      agency: 'इकोपावर सॉल्यूशंस',
      state: 'गुजरात',
      district: 'सूरत',
      constituency: 'सूरत',
      sanctionedAmount: '₹2.00 करोड़',
      disbursedPercent: 100,
      physicalProgressPercent: 100,
      bc_status: 'VERIFIED',
      bc_hash: '0x8f2a...391c',
      alerts: []
    }
  }
};

document.addEventListener('DOMContentLoaded', () => {
 const params = new URLSearchParams(window.location.search);
 if (params.has('persona')) {
 govPersona = params.get('persona');
 }
 if (params.has('lang')) {
 currentLang = params.get('lang');
 }

 applyLanguage(currentLang);
 updateGovPersonaUI(govPersona);

 const searchForm = document.getElementById('gov-search-form');
 if (searchForm) {
 searchForm.addEventListener('submit', (e) => {
 e.preventDefault();
 const val = document.getElementById('gov-project-id-input').value.trim() || 'PROJ-999';
 window.location.href = `gov_dashboard.html?id=${encodeURIComponent(val)}&persona=${govPersona}&lang=${currentLang}`;
 });
 }

 if (window.location.pathname.includes('gov_dashboard.html')) {
 loadGovDashboardData();
 }
});

/**
 * Toggle Language between 'en' and 'hi'
 */
function toggleLanguage(langKey) {
 if (langKey) {
 currentLang = langKey;
 } else {
 currentLang = currentLang === 'en' ? 'hi' : 'en';
 }

 // Preserve URL params
 const url = new URL(window.location);
 url.searchParams.set('lang', currentLang);
 window.history.pushState({}, '', url);

 applyLanguage(currentLang);
 updateGovPersonaUI(govPersona);

 if (window.location.pathname.includes('gov_dashboard.html')) {
 loadGovDashboardData();
 }
}

function applyLanguage(lang) {
 const t = TRANSLATIONS[lang] || TRANSLATIONS['en'];

 // Update Toggle Button Text & State
 const btnToggle = document.getElementById('lang-toggle-btn');
 if (btnToggle) {
 btnToggle.innerHTML = lang === 'en' ? ' <strong>English</strong> | हिंदी' : ' English | <strong>हिंदी</strong>';
 }

 // Update All Static Text Nodes by Data Attributes or IDs
 setText('top-gov-text', t.topGovText);
 setText('top-satyamev', t.satyamev);
 setText('top-skip', t.skipContent);
 setText('header-title', t.ministryTitle);
 setText('header-sub', t.ministrySub);

 setText('nav-home', t.navHome);
 setText('nav-about', t.navAbout);
 setText('nav-audit', t.navAudit);
 setText('nav-state', t.navState);
 setText('nav-mp', t.navMp);
 setText('nav-help', t.navHelp);
 setText('nav-login', t.navLogin);
 setText('nav-back', t.navBack);

 setText('ticker-label', t.tickerLabel);
 setText('ticker-text', t.tickerText);
 setText('persona-label', t.personaSelectLabel);

 setText('btn-persona-ministry', t.btnMinistry);
 setText('btn-persona-state', t.btnState);
 setText('btn-persona-district', t.btnDistrict);
 setText('btn-persona-mp', t.btnMp);

 setText('search-heading', t.searchHeading);
 setText('search-desc', t.searchDesc);
 setText('search-btn', t.searchBtn);
 setText('preset-label', t.presetLabel);
 setText('preset-high-risk', t.presetHighRisk);
 setText('preset-on-track', t.presetOnTrack);

 setText('dashboards-title', t.dashboardsTitle);
 setText('card-ministry-title', t.cardMinistryTitle);
 setText('card-ministry-desc', t.cardMinistryDesc);
 setText('card-state-title', t.cardStateTitle);
 setText('card-state-desc', t.cardStateDesc);
 setText('card-district-title', t.cardDistrictTitle);
 setText('card-district-desc', t.cardDistrictDesc);
 setText('card-mp-title', t.cardMpTitle);
 setText('card-mp-desc', t.cardMpDesc);

 document.querySelectorAll('.launch-btn-text').forEach(btn => {
 btn.textContent = t.launchBtn;
 });

 setText('spec-heading', t.specHeading);
 setText('high-priority-tag', t.highPriorityTag);
 setText('hash-verified-tag', t.hashVerifiedTag);
 setText('alerts-header', t.alertsHeader);
 setText('alerts-desc', t.alertsDesc);

 setText('sat-header', t.satHeader);
 setText('sat-desc', t.satDesc);
 setText('fetch-sat-btn', t.fetchSatBtn);
 setText('audit-exif-btn', t.auditExifBtn);
 setText('gnn-header', t.gnnHeader);
 setText('gnn-desc', t.gnnDesc);
 setText('gnn-box', t.gnnBox);
 setText('sat-box-title', t.satBoxTitle);

 setText('footer-links', t.footerLinks);
 setText('footer-policies', t.footerPolicies);
 setText('footer-contact', t.footerContact);
 setText('footer-managed-by', t.footerManagedBy);
 setText('footer-hosted-by', t.footerHostedBy);

 // Set input placeholder
 const inputElem = document.getElementById('gov-project-id-input');
 if (inputElem) inputElem.placeholder = t.searchInputPlaceholder;
}

function setText(id, text) {
 const elem = document.getElementById(id);
 if (elem) {
 if (!text) {
 elem.style.display = 'none';
 } else {
 elem.style.display = '';
 elem.textContent = text;
 }
 }
}

function setGovPersona(key) {
 const personaMap = GOV_PERSONAS[currentLang] || GOV_PERSONAS['en'];
 if (!personaMap[key]) return;
 govPersona = key;

 if (window.location.pathname.includes('gov_dashboard.html')) {
 const url = new URL(window.location);
 url.searchParams.set('persona', key);
 window.history.pushState({}, '', url);
 loadGovDashboardData();
 }

 updateGovPersonaUI(key);
}

function updateGovPersonaUI(key) {
 const personaMap = GOV_PERSONAS[currentLang] || GOV_PERSONAS['en'];
 const config = personaMap[key];
 if (!config) return;

 document.querySelectorAll('.gov-persona-btn').forEach(btn => {
 btn.classList.toggle('active', btn.dataset.persona === key);
 });

 const elTitle = document.getElementById('gov-banner-title');
 const elSub = document.getElementById('gov-banner-sub');
 if (elTitle) elTitle.textContent = config.title;
 if (elSub) elSub.textContent = config.subtitle;

 const elMetrics = document.getElementById('gov-metrics-container');
 if (elMetrics && config.metrics) {
 elMetrics.innerHTML = config.metrics.map(m => `
 <div class="gov-metric-box ${m.type}">
 <div class="gov-metric-title">${m.title}</div>
 <div class="gov-metric-num">${m.value}</div>
 <div class="gov-metric-desc">${m.sub}</div>
 </div>
 `).join('');
 }
}

function quickLoadGov(id) {
 window.location.href = `gov_dashboard.html?id=${encodeURIComponent(id)}&persona=${govPersona}&lang=${currentLang}`;
}

async function loadGovDashboardData() {
 const params = new URLSearchParams(window.location.search);
 const projectId = params.get('id') || 'PROJ-999';

 const dbMap = GOV_ALERTS_DB[currentLang] || GOV_ALERTS_DB['en'];
 let project = dbMap[projectId] || dbMap['PROJ-999'];
 const t = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];

 

 const elId = document.getElementById('gov-display-project-id');
 const elTitle = document.getElementById('gov-display-project-name');
 const elMeta = document.getElementById('gov-display-project-meta');
 const elProgress = document.getElementById('gov-display-progress-summary');

 if (elId) elId.textContent = `${project.id}`;
 if (elTitle) elTitle.textContent = project.title;
 if (elMeta) {
 elMeta.textContent = `Agency: ${project.agency} | Sanctioned Amount: ${project.sanctionedAmount} | District: ${project.district} (${project.state})`;
 }
 if (elProgress) {
 const gap = project.disbursedPercent - project.physicalProgressPercent;
 elProgress.innerHTML = `
 <strong>${t.disbursedLabel}</strong> ${project.disbursedPercent}% &nbsp;|&nbsp; 
 <strong>${t.progressLabel}</strong> ${project.physicalProgressPercent}% &nbsp;|&nbsp; 
 <strong>${t.gapLabel}</strong> <span style="color: ${gap > 30 ? '#d9534f' : '#5cb85c'}; font-weight: 700;">${gap}% Deviation</span>
 `;
 }

  const alertContainer = document.getElementById('gov-alert-feed-container');
  if (alertContainer) {
    alertContainer.innerHTML = `
      <div style="text-align: center; padding: 3rem; background: white; border: 1px solid #ccc; border-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
        <button id="trigger-ai-btn" class="gov-btn gov-btn-saffron" style="font-size: 1.1rem; padding: 0.8rem 2rem; cursor: pointer; transition: 0.2s;">
          <span id="ai-btn-text">🚀 Initiate AI Compliance Scan</span>
        </button>
        <p style="margin-top: 1rem; color: #555; font-size: 0.95rem; font-family: monospace; height: 1.5rem;" id="ai-loading-text"></p>
      </div>
    `;

    document.getElementById('trigger-ai-btn').addEventListener('click', function() {
      const btn = this;
      const text = document.getElementById('ai-loading-text');
      btn.style.display = 'none';
      text.innerHTML = '<i>Initializing Isolation Forest Anomaly Detection...</i>';
      
      setTimeout(() => { text.innerHTML = '<i>Running FAISS Semantic Similarity Check...</i>'; }, 800);
      setTimeout(() => { text.innerHTML = '<i>Calculating XGBoost Delay Risk Matrix...</i>'; }, 1700);
      setTimeout(() => { 
        renderGovAlertFeed(project.alerts);
      }, 2600);
    });
  }
}

function renderGovAlertFeed(alerts) {
 const container = document.getElementById('gov-alert-feed-container');
 if (!container) return;
 const t = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];

 if (!alerts || alerts.length === 0) {
 container.innerHTML = `
 <div style="padding: 1.5rem; text-align: center; color: #5cb85c; background: white; border: 1px solid #ccc;">
 No compliance alerts or anomalies detected. Project adheres to standard MPLADS guidelines.
 </div>
 `;
 return;
 }

 container.innerHTML = alerts.map(a => `
 <div class="gov-alert-notice severity-${a.severity}">
 <div class="gov-notice-header">
 <div class="gov-notice-title">${a.title}</div>
 <span class="gov-tag tag-${a.severity.toLowerCase()}">${a.severity}</span>
 </div>
 <div class="gov-notice-body">
 ${a.message}
 </div>
 <div class="gov-notice-action-req">
 <strong>${t.recAction}</strong> ${a.actionRequired}
 </div>
 <div class="gov-notice-buttons">
 <button type="button" class="gov-btn gov-btn-saffron gov-btn-sm" onclick="triggerGovAction('Compliance Notice Issued', '${a.type}')">
 ${t.btnNotice}
 </button>
 <button type="button" class="gov-btn gov-btn-danger gov-btn-sm" onclick="triggerGovAction('Payment Release Frozen', '${a.type}')">
 ${t.btnFreeze}
 </button>
 <button type="button" class="gov-btn gov-btn-secondary gov-btn-sm" onclick="triggerGovAction('Hash Ledger Verified', '${a.type}')">
 ${t.btnHash}
 </button>
 </div>
 </div>
 `).join('');
}

function triggerGovAction(action, alertType) {
 const toast = document.getElementById('gov-toast-box');
 if (toast) {
 toast.textContent = `Action Logged: [${action}] (${alertType}) - Recorded in NIRMAAN System Audit Trail.`;
 toast.classList.remove('hidden');
 setTimeout(() => toast.classList.add('hidden'), 5000);
 }
}
