export const sampleProjects = [
  {
    "id": "MPLAD-2024-1042",
    "title": "Construction of community hall in Village X",
    "description": "Construction of community hall in Village X",
    "constituency": "Varanasi",
    "district": "Varanasi",
    "state": "Uttar Pradesh",
    "mp_name": "Hon. Member of Parliament A",
    "category": "Community Infrastructure",
    "sanction_amount": 1500000,
    "sanction_date": "2024-01-15",
    "execution_start": "2024-02-01",
    "execution_end": "2024-08-30",
    "implementing_agency": "Rural Engineering Department",
    "status": "In Progress",
    "coordinates": { "lat": 25.3176, "lng": 82.9739 }
  },
  {
    "id": "MPLAD-2025-0319",
    "title": "Development of public community centre in Village X",
    "description": "Development of public community centre in Village X",
    "constituency": "Varanasi",
    "district": "Varanasi",
    "state": "Uttar Pradesh",
    "mp_name": "Hon. Member of Parliament A",
    "category": "Community Infrastructure",
    "sanction_amount": 1450000,
    "sanction_date": "2024-05-10",
    "execution_start": "2024-04-01",
    "execution_end": "2024-11-30",
    "implementing_agency": "Public Works Department (PWD)",
    "status": "Sanctioned",
    "coordinates": { "lat": 25.3180, "lng": 82.9741 }
  },
  {
    "id": "MPLAD-2024-2088",
    "title": "Installation of 50 High-Mast Solar Street Lights in Block B, Thane West",
    "description": "Supply and installation of 50 standalone solar powered LED street lights along major crossroads and public spaces in Block B, Thane West.",
    "constituency": "Thane",
    "district": "Thane",
    "state": "Maharashtra",
    "mp_name": "Hon. Member of Parliament B",
    "category": "Public Energy & Amenities",
    "sanction_amount": 2200000,
    "sanction_date": "2024-03-10",
    "execution_start": "2024-03-25",
    "execution_end": "2024-09-15",
    "implementing_agency": "Thane Municipal Corporation",
    "status": "Completed",
    "coordinates": { "lat": 19.2183, "lng": 72.9781 }
  },
  {
    "id": "MPLAD-2024-3105",
    "title": "Erection of Solar Powered Illumination Lamps in Block B Area, Thane",
    "description": "Providing and installing solar light poles for evening illumination in residential pockets and junctions of Block B, Thane West zone.",
    "constituency": "Thane",
    "district": "Thane",
    "state": "Maharashtra",
    "mp_name": "Hon. Member of Parliament B",
    "category": "Public Energy & Amenities",
    "sanction_amount": 2150000,
    "sanction_date": "2024-04-02",
    "execution_start": "2024-04-20",
    "execution_end": "2024-10-30",
    "implementing_agency": "Maharashtra Energy Development Agency",
    "status": "Sanctioned",
    "coordinates": { "lat": 19.2186, "lng": 72.9785 }
  },
  {
    "id": "MPLAD-2023-4011",
    "title": "Construction of CC Road from Main Market to Primary School, Village Sultanpur",
    "description": "Cement concrete road construction work covering 1.2 km stretch connecting Main Market Chowk to Government Primary School in Village Sultanpur.",
    "constituency": "Amethi",
    "district": "Amethi",
    "state": "Uttar Pradesh",
    "mp_name": "Hon. Member of Parliament C",
    "category": "Roads & Connectivity",
    "sanction_amount": 2800000,
    "sanction_date": "2023-11-05",
    "execution_start": "2023-12-01",
    "execution_end": "2024-05-30",
    "implementing_agency": "District Rural Development Agency (DRDA)",
    "status": "Completed",
    "coordinates": { "lat": 26.1584, "lng": 81.8015 }
  },
  {
    "id": "MPLAD-2024-4099",
    "title": "Paving of Cement Concrete Road Segment 1, Village Sultanpur",
    "description": "Laying of heavy-duty CC road path starting from Market area towards Primary School boundary in Village Sultanpur.",
    "constituency": "Amethi",
    "district": "Amethi",
    "state": "Uttar Pradesh",
    "mp_name": "Hon. Member of Parliament C",
    "category": "Roads & Connectivity",
    "sanction_amount": 1400000,
    "sanction_date": "2024-01-10",
    "execution_start": "2024-02-01",
    "execution_end": "2024-06-15",
    "implementing_agency": "District Rural Development Agency (DRDA)",
    "status": "In Progress",
    "coordinates": { "lat": 26.1586, "lng": 81.8018 }
  },
  {
    "id": "MPLAD-2024-5001",
    "title": "Deep Tube Well Drinking Water Facility with Hand Pump at Panchayat Bhavan, Wayanad",
    "description": "Boring of 300ft deep tube well and installation of India Mark II hand pump with stainless steel tank at Panchayat Bhavan premises, Wayanad.",
    "constituency": "Wayanad",
    "district": "Wayanad",
    "state": "Kerala",
    "mp_name": "Hon. Member of Parliament D",
    "category": "Drinking Water",
    "sanction_amount": 450000,
    "sanction_date": "2024-02-12",
    "execution_start": "2024-03-01",
    "execution_end": "2024-05-15",
    "implementing_agency": "Kerala Water Authority",
    "status": "Completed",
    "coordinates": { "lat": 11.6854, "lng": 76.1320 }
  },
  {
    "id": "MPLAD-2024-5055",
    "title": "Drinking Water Borewell Installation at Panchayat Complex, Wayanad",
    "description": "Installation of deep drinking water borewell and pumping unit inside Panchayat Bhavan compound to mitigate summer water scarcity in Wayanad.",
    "constituency": "Wayanad",
    "district": "Wayanad",
    "state": "Kerala",
    "mp_name": "Hon. Member of Parliament D",
    "category": "Drinking Water",
    "sanction_amount": 480000,
    "sanction_date": "2024-03-01",
    "execution_start": "2024-03-15",
    "execution_end": "2024-06-30",
    "implementing_agency": "Groundwater Department",
    "status": "Sanctioned",
    "coordinates": { "lat": 11.6855, "lng": 76.1322 }
  }
];
